/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QualificationsRouteImport } from './routes/qualifications'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAccountingRouteImport } from './routes/services.accounting'
import { Route as ServicesFinancialServicesRouteImport } from './routes/services.financial-services'
import { Route as ServicesTaxationRouteImport } from './routes/services.taxation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificationsRoute = QualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccountingRoute = ServicesAccountingRouteImport.update({
  id: '/services/accounting',
  path: '/services/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFinancialServicesRoute =
  ServicesFinancialServicesRouteImport.update({
    id: '/services/financial-services',
    path: '/services/financial-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesTaxationRoute = ServicesTaxationRouteImport.update({
  id: '/services/taxation',
  path: '/services/taxation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/qualifications': typeof QualificationsRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/financial-services': typeof ServicesFinancialServicesRoute
  '/services/taxation': typeof ServicesTaxationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/qualifications': typeof QualificationsRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/financial-services': typeof ServicesFinancialServicesRoute
  '/services/taxation': typeof ServicesTaxationRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/qualifications': typeof QualificationsRoute
  '/resources': typeof ResourcesRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/financial-services': typeof ServicesFinancialServicesRoute
  '/services/taxation': typeof ServicesTaxationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/qualifications'
    | '/resources'
    | '/testimonials'
    | '/services/accounting'
    | '/services/financial-services'
    | '/services/taxation'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/qualifications'
    | '/resources'
    | '/testimonials'
    | '/services/accounting'
    | '/services/financial-services'
    | '/services/taxation'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/qualifications'
    | '/resources'
    | '/testimonials'
    | '/services/accounting'
    | '/services/financial-services'
    | '/services/taxation'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  QualificationsRoute: typeof QualificationsRoute
  ResourcesRoute: typeof ResourcesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ServicesAccountingRoute: typeof ServicesAccountingRoute
  ServicesFinancialServicesRoute: typeof ServicesFinancialServicesRoute
  ServicesTaxationRoute: typeof ServicesTaxationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualifications': {
      id: '/qualifications'
      path: '/qualifications'
      fullPath: '/qualifications'
      preLoaderRoute: typeof QualificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accounting': {
      id: '/services/accounting'
      path: '/services/accounting'
      fullPath: '/services/accounting'
      preLoaderRoute: typeof ServicesAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/financial-services': {
      id: '/services/financial-services'
      path: '/services/financial-services'
      fullPath: '/services/financial-services'
      preLoaderRoute: typeof ServicesFinancialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/taxation': {
      id: '/services/taxation'
      path: '/services/taxation'
      fullPath: '/services/taxation'
      preLoaderRoute: typeof ServicesTaxationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  QualificationsRoute: QualificationsRoute,
  ResourcesRoute: ResourcesRoute,
  TestimonialsRoute: TestimonialsRoute,
  ServicesAccountingRoute: ServicesAccountingRoute,
  ServicesFinancialServicesRoute: ServicesFinancialServicesRoute,
  ServicesTaxationRoute: ServicesTaxationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
